# This file was generated by GoReleaser. DO NOT EDIT.
cask "etui" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bab20c6aee85d202ef2f3e7df2d769bd21f34995c95e34b9ae483a1fd43abf29"
      url "https://github.com/ianaya89/etui/releases/download/v#{version}/etui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52c38849ef15aab4d359923dbebf5d3cf4355e4307e8b2735f001bcb556ad774"
      url "https://github.com/ianaya89/etui/releases/download/v#{version}/etui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "810e8f785a1186a458dd664bde9200b221300823a736feae2a685f42293c5657"
      url "https://github.com/ianaya89/etui/releases/download/v#{version}/etui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83e46346054e1f1637409f066e4d273ceef2b3577aaa81d90133a5567da67184"
      url "https://github.com/ianaya89/etui/releases/download/v#{version}/etui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "etui"
  desc "Terminal UI for browsing and managing etcd clusters"
  homepage "https://github.com/ianaya89/etui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "etui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/etui"]
    end
  end

  # No zap stanza required

end
