# This file was generated by GoReleaser. DO NOT EDIT.
cask "hatch" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cff8c3b5b648297e4c5a70f7d9a0bf0d7a0e26db4cb369cce41c4c68c00bc8ea"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0457bf3dd369d646639da486c8ce4b121f00ee383add6b0e145bf23440d4a4f"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1701df6169ff4f4fb84e0d3abb1c58318a6142a61a0da7285c92c0e789ede88"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "274a109c868b037bd0bf01c83f88451eeecf312bb2d16ad052ebbf8057dc6420"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hatch"
  desc "Move your dev setup to a new machine, peer to peer"
  homepage "https://github.com/ianaya89/hatch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hatch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/hatch"]
    end
  end

  # No zap stanza required

end
