# This file was generated by GoReleaser. DO NOT EDIT.
cask "hatch" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "71e00b6961b78f8804694195ac39549f802fa1ec1ff907fdf254025230794a84"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c4bb03547843f8038852816e254649c9ae624095d60fb9b012c13afb5e04d8cc"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "084a02a1057d56f9b9ab9105fa037f6684fa427b4ec398778987ca1078bc6aef"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ec08152b31fe82a05a07b612e86884da66551444f3755f5ca2df0b6742981774"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hatch"
  desc "Move your dev setup to a new machine, peer to peer"
  homepage "https://github.com/ianaya89/hatch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hatch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/hatch"]
    end
  end

  # No zap stanza required
end
