# This file was generated by GoReleaser. DO NOT EDIT.
cask "hatch" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "af0b44f18012a8b7ff34f056e6fb7b33283357d40f4daa597f06627bb0a6ce80"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d3663a451d4978dae64f48f5365d923fb9cdeb7c0cc5f9a577aee1fad949d77"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "edd2191cfce4aa199e0890e384520e8e27225aa3ae65b7463e23aecdd161f16e"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc18e894402f1653b153116e49609bd20de1ab433d235f1e52b5b0ac386bda7a"
      url "https://github.com/ianaya89/hatch/releases/download/v#{version}/hatch_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hatch"
  desc "Move your dev setup to a new machine, peer to peer"
  homepage "https://github.com/ianaya89/hatch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hatch"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/hatch"]
    end
  end

  # No zap stanza required
end
