# This file was generated by GoReleaser. DO NOT EDIT.
cask "pad" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d23614def686d256f5b305460f75e26948021b1932bdc3060dc3bc864967cb39"
      url "https://github.com/ianaya89/scratchpad/releases/download/v#{version}/pad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4569e4c91e3c0d9d5419724142119c432b17af188a461ae0409090e3d21d5cfa"
      url "https://github.com/ianaya89/scratchpad/releases/download/v#{version}/pad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9042ea9f7f14a613c6dc0ae28e66e6e7cfbc88a8634e14511e4af6bebd2dee2"
      url "https://github.com/ianaya89/scratchpad/releases/download/v#{version}/pad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "21fefb24410ee3b7d5a3f0056cca5af9e9b5ef548071dc260cbaa0ebd5b538a8"
      url "https://github.com/ianaya89/scratchpad/releases/download/v#{version}/pad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pad"
  desc "Tabbed terminal scratchpad"
  homepage "https://github.com/ianaya89/scratchpad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/pad"]
    end
  end

  # No zap stanza required

end
