# This file was generated by GoReleaser. DO NOT EDIT.
cask "pad" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "db77536d2eac0d77397671770c44d6a00489d736f796f3e0da51731da64e4031"
      url "https://github.com/ianaya89/pad/releases/download/v#{version}/pad_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c3fe4137f5b061a740f30beed943608c0b8599f9d1e82100d98f448b36a836ee"
      url "https://github.com/ianaya89/pad/releases/download/v#{version}/pad_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb754743ee8ceea06f5c41b698e9b0693a1c57e5747ac6f8eb84d542d1199c75"
      url "https://github.com/ianaya89/pad/releases/download/v#{version}/pad_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31b18a5a7438c33d0c9bbee72fd889d666b3f3f35d8c3ae3f133b99e77c5a6a9"
      url "https://github.com/ianaya89/pad/releases/download/v#{version}/pad_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pad"
  desc "Tabbed terminal scratchpad"
  homepage "https://github.com/ianaya89/scratchpad"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/pad"]
    end
  end

  # No zap stanza required

end
