# This file was generated by GoReleaser. DO NOT EDIT.
cask "remind" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "062f42c7716e1afa785e0543078c361438191c7057b43998b3ebec628b95549d"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a5d990a85f18f7988e78a9335dbc2f5bb3e8fd0f176c70e7ba7c393bbb3df60"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c285aa567c616f97c9f33e02127c68f6dc181fbc34391325d34be2c7deb7adc"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f68cccdc55d439ca1a4eaafb5c01730ebec5b8be7da3e6266897ee2529b5ef59"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remind"
  desc "Terminal reminders with OS + phone notifications"
  homepage "https://github.com/ianaya89/remind"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/remind"]
    end
  end

  # No zap stanza required

end
