# This file was generated by GoReleaser. DO NOT EDIT.
cask "remind" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "6ea3d9182d16b434647f64078a138de79584d136db5a707b4059cc7f37ebd396"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce37ae8079f0a56b5f3d345c7ab677cd098c205270bbd8b626b840bf69243688"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c246de5cbba7b556404385bc6a17a008f686889ebefa8492a1de8619778fdf74"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56ddee7b94ccc8e41f8f394b88ead1a2bb1ed285f2f6d9d1b73f003616315d21"
      url "https://github.com/ianaya89/remind/releases/download/v#{version}/remind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remind"
  desc "Terminal reminders with OS + phone notifications"
  homepage "https://github.com/ianaya89/remind"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remind"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/remind"]
    end
  end

  # No zap stanza required

end
