# This file was generated by GoReleaser. DO NOT EDIT.
cask "termiedos" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4a10f9d5a12637ff2db2b427350a0cc9837e65eb2b7ea4ed66bb862def127126"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d3b30a5bee84d6d1869f7fd09c3ae05b9357203d3fde0333f87089ac4e1cd2f"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8a7ce7ee26d7e0ca0214dda48279886201fc776f4b68a5d02bcaff1eb6d7962"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4036bb4f60a93b5d090dcf7865bd602c13b57f50c400031da2e659ff93a21e1a"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termiedos"
  desc "Resultados de fútbol en la terminal (promiedos)"
  homepage "https://github.com/ianaya89/termiedos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termiedos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/termiedos"]
    end
  end

  # No zap stanza required

end
