# This file was generated by GoReleaser. DO NOT EDIT.
cask "termiedos" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "be29d810292ae4d8c05e844416a74c475624ce6721967ac0966601e506739821"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d508c14ebe98395813e48a2b91fd8fe69fd591b2d3fabe8a9e5d90bee02c2a8b"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "674ae66c5a89560dbce67f83d83ba4a50a11427b22927bb776431be603626b62"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "074e79be9aa0fc0e1318e2fc7643a16df39f55d6df6db2bd119e017dc3f0b943"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termiedos"
  desc "Resultados de fútbol en la terminal (promiedos)"
  homepage "https://github.com/ianaya89/termiedos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termiedos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/termiedos"]
    end
  end

  # No zap stanza required

end
