# This file was generated by GoReleaser. DO NOT EDIT.
cask "termiedos" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "98a005bedd88fb7a344ad16cfc267ede1b084571b9e85dd4ea042b5e59ea14a6"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9bd8b1b408b48b8e99c1c128e62beaa5a8645c62bfa31dbc8eb3cac447c57097"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e0f3765ac63b0e7ceb5996f190161be0e18cbd06be6e5df975ad8a05641bb97"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad0c2a40d7c13000ad1b991904ffc1a5e13692e3477d7881fdee1b987bebd295"
      url "https://github.com/ianaya89/termiedos/releases/download/v#{version}/termiedos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termiedos"
  desc "Resultados de fútbol en la terminal (promiedos)"
  homepage "https://github.com/ianaya89/termiedos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termiedos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/termiedos"]
    end
  end

  # No zap stanza required

end
